# Quarkus Calendars Configuration

quarkus:
  application:
    name: quarkus-calendars

# Google Calendars Configuration
google:
  calendar:
    # Path to service account credentials JSON file
    service-account-key: ${GOOGLE_SERVICE_ACCOUNT_KEY_PATH:service-account.json}
    application-name: ${quarkus.application.name}
    calendars:
      releases:
        # Calendar ID from env var or empty (will fail if not set)
        id: ${GOOGLE_CALENDAR_RELEASES_ID:}
        name: quarkus-releases
      calls:
        # Calendar ID from env var or empty (will fail if not set)
        id: ${GOOGLE_CALENDAR_CALLS_ID:}
        name: quarkus-calls

# Reconciliation Configuration
reconciliation:
  # Number of months before today to include in reconciliation (default: 1)
  months-before: 1
  # Number of months after today to include in reconciliation (default: 4)
  months-after: 4
